### PR TITLE
Upgrade to vaadin 8.2.1

### PR DESCRIPTION
**Pull request by a-schild**
Version for Vaadin 8.2.1

### CODE REVIEW

**Comment by peergynt** [comment]
@a-schild Thank you for the PR. I moved the old Vaadin 7 code in a separate branch and updated master to work with Vaadin 8 (I went with vaadin 8.2.0 in the POM - should work fine with 8.2.1). I also did a little bit more cleanup and fixed the demo.
If you can give master a try, let me know if that works for you.

**Comment by a-schild** [comment]
Trunk works fine with vaadin 8.2.1
Please don't forget to update Readme.MD to say which version is fro Vaadin 7 / 8

**Comment by peergynt** [comment]
Will do. I'll push out a new release in a few days unless I hear otherwise.

**Comment by a-schild** [comment]
Ok,

thanks for the fast answer

**Pull request closed without merging**
